import type { Metadata } from 'next'
import { Navbar } from '@/components'

export const metadata: Metadata = {
  title: 'Public Layout',
  description: 'Generated by create next app'
}

export default function PublicLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navbar />
      <h1>Public Layout</h1>
      {children}
    </>
  )
}
